version: "3"
 
services:
  postgis:
    image: "mdillon/postgis:latest"
    ports:
      - "5432:5432"
    volumes:
      - postgis:/var/lib/postgresql/data
 
  app:
    depends_on:
      - "postgis"
    build: .
    command: bash start
    ports:
      - "3000:3000"
    volumes:
      - .:/onebittinder_api
      - gems:/gems
 
volumes:
  postgis:
  gems: